use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn truthy_env(name: &str) -> bool {
    matches!(
        env::var(name).ok().as_deref(),
        Some("1") | Some("true") | Some("TRUE") | Some("yes") | Some("YES")
    )
}

fn main() {
    // 1. Get Git commit hash
    let commit = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    // 2. Get build date
    let date = Command::new("date")
        .arg("+%Y-%m-%d")
        .output()
        .ok()
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=GIT_COMMIT={}", commit);
    println!("cargo:rustc-env=BUILD_DATE={}", date);

    // 3. Build the runner stub (Independent of Workspace)
    let root_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let runner_dir = Path::new(&root_dir).join("crates/matchbox-runner");
    let stub_dest_dir = Path::new(&root_dir).join("stubs");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not found");
    let stub_target_dir = Path::new(&out_dir).join("runner_target");
    let src_dir = Path::new(&root_dir).join("src");
    let stubs_rs_path = src_dir.join("stubs.rs");

    // Ensure stubs directory exists
    if !stub_dest_dir.exists() {
        fs::create_dir_all(&stub_dest_dir).expect("Failed to create stubs directory");
    }

    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());

    println!("cargo:rerun-if-changed=crates/matchbox-runner/src/main.rs");
    println!("cargo:rerun-if-changed=crates/matchbox-runner/Cargo.toml");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/src/vm/mod.rs");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/src/vm/intern.rs");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/src/vm/opcode.rs");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/src/bifs");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/src/types");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/src/lib.rs");
    println!("cargo:rerun-if-changed=crates/matchbox-vm/Cargo.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let mut stubs_rs_content = String::from("// @generated by build.rs. Do not edit.\n");
    stubs_rs_content.push_str("use anyhow::{Result, anyhow, bail};\n\n");
    stubs_rs_content.push_str("static STUBS: &[(&str, &[u8])] = &[\n");

    // Get enabled features to pass to the stub build
    let mut features = Vec::new();
    if env::var("CARGO_FEATURE_BIF_IO").is_ok() {
        features.push("bif-io");
    }
    if env::var("CARGO_FEATURE_BIF_HTTP").is_ok() {
        features.push("bif-http");
    }
    if env::var("CARGO_FEATURE_BIF_ZIP").is_ok() {
        features.push("bif-zip");
    }
    if env::var("CARGO_FEATURE_BIF_CRYPTO").is_ok() {
        features.push("bif-crypto");
    }
    if env::var("CARGO_FEATURE_BIF_CLI").is_ok() {
        features.push("bif-cli");
    }

    // Helper closure to build and copy a stub
    let build_stub = |target: Option<&str>,
                      dest_name: &str,
                      src_name: &str,
                      alias: &str,
                      stubs_rs: &mut String,
                      enabled_features: &[&str]|
     -> bool {
        let dest_path = stub_dest_dir.join(dest_name);

        // Determine whether we need (re)build: missing stub, zero-length stub,
        // or any tracked source file is newer than the stub.
        let sources_to_watch = [
            Path::new(&root_dir).join("crates/matchbox-runner/src/main.rs"),
            Path::new(&root_dir).join("crates/matchbox-runner/Cargo.toml"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/vm/mod.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/vm/intern.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/vm/opcode.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/bifs/mod.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/types/mod.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/lib.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/Cargo.toml"),
        ];
        let stub_mtime = dest_path.metadata().and_then(|m| m.modified()).ok();
        let needs_rebuild = stub_mtime.map_or(true, |stub_time| {
            fs::metadata(&dest_path)
                .map(|m| m.len() == 0)
                .unwrap_or(true)
                || sources_to_watch.iter().any(|src| {
                    src.metadata()
                        .and_then(|m| m.modified())
                        .map(|src_time| src_time > stub_time)
                        .unwrap_or(false)
                })
        });

        let mut use_stub = !needs_rebuild;

        if needs_rebuild {
            let mut cmd = Command::new(&cargo);
            cmd.arg("build")
                .arg("--release")
                .current_dir(&runner_dir)
                .env("CARGO_TARGET_DIR", &stub_target_dir);

            if !enabled_features.is_empty() {
                cmd.arg("--features").arg(enabled_features.join(","));
            }

            if let Some(t) = target {
                cmd.arg("--target").arg(t);
            }

            let output = cmd.output();

            let mut success = false;
            if let Ok(out) = output {
                if out.status.success() {
                    let mut src_path = stub_target_dir.clone();
                    if let Some(t) = target {
                        src_path = src_path.join(t);
                    }
                    src_path = src_path.join("release").join(src_name);

                    if fs::copy(&src_path, &dest_path).is_ok() {
                        success = true;
                        use_stub = true;
                        println!(
                            "cargo:warning=Runner stub built and copied to {}",
                            dest_path.display()
                        );
                    } else {
                        println!(
                            "cargo:warning=Failed to copy stub from {} to {}",
                            src_path.display(),
                            dest_path.display()
                        );
                    }
                } else {
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let stdout = String::from_utf8_lossy(&out.stdout);
                    println!(
                        "cargo:warning=Failed to build stub: {}. Error: {}",
                        dest_name, stderr
                    );
                    if !stdout.is_empty() {
                        println!("cargo:warning=Stdout: {}", stdout);
                    }
                }
            } else if let Err(e) = output {
                println!(
                    "cargo:warning=Failed to execute build command for {}: {}",
                    dest_name, e
                );
            }

            if !success {
                println!("cargo:warning=Runner stub was not built: {}.", dest_name);
            }
        } else {
            println!("cargo:warning=Using pre-existing stub for {}", dest_name);
        }

        let available = use_stub && dest_path.metadata().map(|m| m.len() > 0).unwrap_or(false);
        if available {
            stubs_rs.push_str(&format!(
                "    (\n        \"{}\",\n        include_bytes!(\"../stubs/{}\"),\n    ),\n",
                alias, dest_name
            ));
            if let Some(t) = target {
                stubs_rs.push_str(&format!(
                    "    (\n        \"{}\",\n        include_bytes!(\"../stubs/{}\"),\n    ),\n",
                    t, dest_name
                ));
            }
        } else {
            println!(
                "cargo:warning=Runner stub {} is unavailable; it will not be embedded",
                dest_name
            );
        }
        available
    };

    let host = env::var("TARGET").unwrap_or_else(|_| "unknown".to_string());

    // Always build WASI if possible
    build_stub(
        Some("wasm32-wasip1"),
        "runner_stub_wasip1.wasm",
        "matchbox_runner.wasm",
        "wasi",
        &mut stubs_rs_content,
        &features,
    );

    // Always build web WASM if possible (requires wasm32-unknown-unknown target + js feature)
    let mut web_features = features.clone();
    web_features.push("js");
    build_stub(
        Some("wasm32-unknown-unknown"),
        "runner_stub_wasm32-unknown-unknown.wasm",
        "matchbox_runner.wasm",
        "web",
        &mut stubs_rs_content,
        &web_features,
    );

    // Build ESP32 stubs if possible
    let esp32_targets = vec![
        ("xtensa-esp32-espidf", "runner_stub_esp32.elf"),
        ("xtensa-esp32s3-espidf", "runner_stub_esp32s3.elf"),
        ("riscv32imc-esp-espidf", "runner_stub_esp32c3.elf"),
    ];

    let rebuild_embedded_stubs = truthy_env("MATCHBOX_REBUILD_EMBEDDED_STUBS");

    for (target, dest) in esp32_targets {
        let dest_path = stub_dest_dir.join(dest);

        // Determine whether we need (re)build: missing stub, zero-length stub,
        // or any tracked source file is newer than the stub.
        let sources_to_watch = [
            Path::new(&root_dir).join("crates/matchbox-esp32-runner/src/main.rs"),
            Path::new(&root_dir).join("crates/matchbox-esp32-runner/Cargo.toml"),
            Path::new(&root_dir).join("crates/matchbox-esp32-runner/build.rs"),
            Path::new(&root_dir).join("crates/matchbox-vm/src/lib.rs"),
        ];

        let stub_mtime = dest_path.metadata().and_then(|m| m.modified()).ok();
        let is_empty = fs::metadata(&dest_path)
            .map(|m| m.len() == 0)
            .unwrap_or(true);

        let needs_rebuild = stub_mtime.map_or(true, |stub_time| {
            is_empty
                || sources_to_watch.iter().any(|src| {
                    src.metadata()
                        .and_then(|m| m.modified())
                        .map(|src_time| src_time > stub_time)
                        .unwrap_or(false)
                })
        });

        if needs_rebuild && (is_empty || rebuild_embedded_stubs) {
            println!(
                "cargo:warning=Building ESP32 stub for {} (this may take a few minutes)...",
                target
            );
            let mut success = false;

            // Use a completely independent target directory to avoid any lock contention
            let independent_target_dir = Path::new(&root_dir)
                .join("target")
                .join("esp32_stubs")
                .join(target);
            fs::create_dir_all(&independent_target_dir).ok();

            let mut cmd = Command::new("rustup");
            cmd.arg("run")
                .arg("esp")
                .arg("cargo")
                .arg("build")
                .arg("--release")
                .arg("--target")
                .arg(target)
                .arg("--target-dir")
                .arg(&independent_target_dir)
                .arg("--features")
                .arg("embedded-web")
                .current_dir(Path::new(&root_dir).join("crates/matchbox-esp32-runner"))
                .env("BOXLANG_BYTECODE_PATH", "")
                .env_remove("CARGO_MAKEFLAGS")
                .env_remove("MAKEFLAGS")
                .env_remove("CARGO_TARGET_DIR")
                .env_remove("RUSTC")
                .env_remove("CARGO")
                .env_remove("RUSTDOC")
                .env_remove("RUSTFLAGS")
                .env_remove("CARGO_ENCODED_RUSTFLAGS")
                .env_remove("RUSTC_WORKSPACE_WRAPPER");

            // We use output() instead of status() to capture the error.
            match cmd.output() {
                Ok(output) if output.status.success() => {
                    let src_path = independent_target_dir
                        .join(target)
                        .join("release")
                        .join("matchbox-esp32-runner");
                    if fs::copy(&src_path, &dest_path).is_ok() {
                        success = true;
                        println!("cargo:warning=ESP32 stub successfully built for {}", target);
                    } else {
                        println!(
                            "cargo:warning=Failed to copy ESP32 stub from {} to {}",
                            src_path.display(),
                            dest_path.display()
                        );
                    }
                }
                Ok(output) => {
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    let stdout = String::from_utf8_lossy(&output.stdout);
                    println!(
                        "cargo:warning=ESP32 build failed for {} with status: {}",
                        target, output.status
                    );
                    println!("cargo:warning=STDERR: {}", stderr);
                    if !stdout.is_empty() {
                        println!("cargo:warning=STDOUT: {}", stdout);
                    }
                }
                Err(e) => {
                    println!(
                        "cargo:warning=Failed to execute cargo build for ESP32 stub {}: {}",
                        target, e
                    );
                }
            }

            if !success {
                println!("cargo:warning=ESP32 stub was not built: {}.", dest);
            }
        } else if needs_rebuild {
            println!(
                "cargo:warning=Using pre-existing ESP32 stub for {} (set MATCHBOX_REBUILD_EMBEDDED_STUBS=1 to rebuild)",
                target
            );
        }

        if dest_path.metadata().map(|m| m.len() > 0).unwrap_or(false) {
            stubs_rs_content.push_str(&format!(
                "    (\n        \"{}\",\n        include_bytes!(\"../stubs/{}\"),\n    ),\n",
                target, dest
            ));
        } else {
            println!(
                "cargo:warning=ESP32 stub {} is unavailable; it will not be embedded",
                dest
            );
        }
    }

    if cfg!(feature = "cross-compile") {
        let targets = vec![
            (
                "x86_64-unknown-linux-gnu",
                "runner_stub_x86_64-unknown-linux-gnu",
                "matchbox_runner",
            ),
            (
                "i686-unknown-linux-gnu",
                "runner_stub_i686-unknown-linux-gnu",
                "matchbox_runner",
            ),
            (
                "aarch64-unknown-linux-gnu",
                "runner_stub_aarch64-unknown-linux-gnu",
                "matchbox_runner",
            ),
            (
                "armv7-unknown-linux-gnueabihf",
                "runner_stub_armv7-unknown-linux-gnueabihf",
                "matchbox_runner",
            ),
            (
                "x86_64-apple-darwin",
                "runner_stub_x86_64-apple-darwin",
                "matchbox_runner",
            ),
            (
                "aarch64-apple-darwin",
                "runner_stub_aarch64-apple-darwin",
                "matchbox_runner",
            ),
            (
                "x86_64-pc-windows-msvc",
                "runner_stub_x86_64-pc-windows-msvc.exe",
                "matchbox_runner.exe",
            ),
            (
                "aarch64-pc-windows-msvc",
                "runner_stub_aarch64-pc-windows-msvc.exe",
                "matchbox_runner.exe",
            ),
            (
                "x86_64-pc-windows-gnu",
                "runner_stub_x86_64-pc-windows-gnu.exe",
                "matchbox_runner.exe",
            ),
        ];

        for (target, dest, src) in targets {
            // Skip macOS targets on Linux unless specifically requested, as they need osxcross/zig
            if cfg!(target_os = "linux") && target.contains("apple") {
                let dest_path = stub_dest_dir.join(dest);
                if dest_path.metadata().map(|m| m.len() > 0).unwrap_or(false) {
                    stubs_rs_content.push_str(&format!(
                        "    (\n        \"{}\",\n        include_bytes!(\"../stubs/{}\"),\n    ),\n",
                        target, dest
                    ));
                } else {
                    println!(
                        "cargo:warning=Cross-compile stub {} is unavailable; it will not be embedded",
                        dest
                    );
                }
                continue;
            }

            let available = build_stub(
                Some(target),
                dest,
                src,
                target,
                &mut stubs_rs_content,
                &features,
            );
            if target == host {
                if available {
                    stubs_rs_content.push_str(&format!(
                        "    (\n        \"host\",\n        include_bytes!(\"../stubs/{}\"),\n    ),\n",
                        dest
                    ));
                } else {
                    panic!(
                        "Host runner stub for target {} is required but unavailable",
                        host
                    );
                }
            }
        }
    } else {
        let native_src_name = if cfg!(windows) {
            "matchbox_runner.exe"
        } else {
            "matchbox_runner"
        };
        let dest_name = format!("runner_stub_{}", host);
        let available = build_stub(
            None,
            &dest_name,
            native_src_name,
            "host",
            &mut stubs_rs_content,
            &features,
        );
        if available {
            stubs_rs_content.push_str(&format!(
                "    (\n        \"{}\",\n        include_bytes!(\"../stubs/{}\"),\n    ),\n",
                host, dest_name
            ));
        } else {
            panic!(
                "Host runner stub for target {} is required but unavailable",
                host
            );
        }
    }

    stubs_rs_content.push_str("];\n\n");
    stubs_rs_content.push_str("pub fn get_stub(target: &str) -> Result<&'static [u8]> {\n");
    stubs_rs_content.push_str("    let bytes = STUBS\n");
    stubs_rs_content.push_str("        .iter()\n");
    stubs_rs_content.push_str("        .find(|(name, _)| *name == target)\n");
    stubs_rs_content.push_str("        .map(|(_, bytes)| *bytes)\n");
    stubs_rs_content.push_str("        .ok_or_else(|| anyhow!(\"runner stub for target '{}' is not embedded\", target))?;\n\n");
    stubs_rs_content.push_str("    if bytes.is_empty() {\n");
    stubs_rs_content.push_str(
        "        bail!(\"runner stub for target '{}' is embedded but empty\", target);\n",
    );
    stubs_rs_content.push_str("    }\n\n");
    stubs_rs_content.push_str("    Ok(bytes)\n");
    stubs_rs_content.push_str("}\n");

    fs::write(&stubs_rs_path, stubs_rs_content).expect("Failed to write src/stubs.rs");
}
