WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{ ("//" ~ (!"\n" ~ ANY)*) | ("/*" ~ (!"*/" ~ ANY)* ~ "*/") }

program = { SOI ~ statement* ~ EOI }

statement = {
    ( function_decl
    | for_loop
    | if_statement
    | return_stmt
    | expression_stmt
    )
}

function_decl = { "function" ~ identifier ~ "(" ~ params? ~ ")" ~ block }

return_stmt = { "return" ~ expression? ~ ";"? }
params = { identifier ~ ("," ~ identifier)* }

for_loop = { "for" ~ "(" ~ (for_in | for_classic) ~ ")" ~ block }
for_in = { identifier ~ ("," ~ identifier)? ~ "in" ~ expression }
for_classic = { init? ~ ";" ~ condition? ~ ";" ~ update? }
init = { assignment | expression }
condition = { expression }
update = { expression }

if_statement = { "if" ~ "(" ~ expression ~ ")" ~ block ~ ("else" ~ block)? }
block = { "{" ~ statement* ~ "}" }

expression_stmt = { expression ~ ";"? }

expression = {
    assignment
    | binary_expr
}

assignment = { identifier ~ "=" ~ expression }

binary_expr = { primary ~ (operator ~ primary)* }

operator = { "+" | "-" | "*" | "/" | "==" | "!=" | "<=" | ">=" | "<" | ">" | "&" }

primary = { atom ~ (function_call_args | array_access | member_access)* }

atom = {
    literal
    | identifier
    | "(" ~ expression ~ ")"
}

function_call_args = { "(" ~ args? ~ ")" }
array_access = { "[" ~ expression ~ "]" }
member_access = { "." ~ identifier }

function_call = _{ identifier ~ function_call_args }
args = { expression ~ ("," ~ expression)* }

literal = { string | number | boolean | null_lit | array_literal | struct_literal | anonymous_function }

anonymous_function = {
    ("function" ~ "(" ~ params? ~ ")" ~ block) |
    (lambda_params ~ ("=>" | "->") ~ (block | expression))
}
lambda_params = { ("(" ~ params? ~ ")") | identifier }

array_literal = { "[" ~ (expression ~ ("," ~ expression)* ~ ","?)? ~ "]" }

struct_literal = { "{" ~ (struct_member ~ ("," ~ struct_member)* ~ ","?)? ~ "}" }
struct_member = { struct_key ~ (":" | "=") ~ expression }
struct_key = { identifier | string | number }

string = ${
    "\"" ~ string_content_double ~ "\"" |
    "'" ~ string_content_single ~ "'"
}
string_content_double = _{ (interpolation | escaped_hash | string_text_double)* }
string_content_single = _{ (interpolation | escaped_hash | string_text_single)* }

interpolation = !{ "#" ~ expression ~ "#" }
escaped_hash = @{ "##" }
string_text_double = @{ (!("\"" | "#") ~ ANY)+ }
string_text_single = @{ (!("'" | "#") ~ ANY)+ }

number = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }

boolean = { "true" | "false" }

null_lit = { "null" }

identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
