// @generated by build.rs. Do not edit.
use anyhow::{Result, anyhow, bail};

static STUBS: &[(&str, &[u8])] = &[
    ("wasi", include_bytes!("../stubs/runner_stub_wasip1.wasm")),
    (
        "wasm32-wasip1",
        include_bytes!("../stubs/runner_stub_wasip1.wasm"),
    ),
    (
        "web",
        include_bytes!("../stubs/runner_stub_wasm32-unknown-unknown.wasm"),
    ),
    (
        "wasm32-unknown-unknown",
        include_bytes!("../stubs/runner_stub_wasm32-unknown-unknown.wasm"),
    ),
    (
        "host",
        include_bytes!("../stubs/runner_stub_aarch64-apple-darwin"),
    ),
    (
        "aarch64-apple-darwin",
        include_bytes!("../stubs/runner_stub_aarch64-apple-darwin"),
    ),
];

pub fn get_stub(target: &str) -> Result<&'static [u8]> {
    let bytes = STUBS
        .iter()
        .find(|(name, _)| *name == target)
        .map(|(_, bytes)| *bytes)
        .ok_or_else(|| anyhow!("runner stub for target '{}' is not embedded", target))?;

    if bytes.is_empty() {
        bail!("runner stub for target '{}' is embedded but empty", target);
    }

    Ok(bytes)
}
